### PR TITLE
! scala: Refactored into multi-module project

### PR DESCRIPTION
**Pull request by agarbutt**
! scala: Refactored into multi-module project producing kamon-scala, kamon-scalaz, and kamon-twitter.

### CODE REVIEW

**Comment by ivantopo** [comment]
@agarbutt all this effort is awesome, we will definitely use this, but, on the kamon-futures module that wont be out until 0.7.0 is out :/... in order to actually fix #4, could you please strip this down to the bare minimum to just add support for Scala 2.12?

**Comment by agarbutt** [comment]
@ivantopo, sorry about the absence, got distracted with Work work.. ;)  If you have not addressed this already, I will get a PR later today?

**Comment by ivantopo** [comment]
hey @agarbutt, please go ahead and thanks a lot for your contributions! :smile:

**Comment by ivantopo** [comment]
@agarbutt, I saw your commit but I still see that twitter/scalaz futures are gone, was that intentional or still WIP?

**Comment by agarbutt** [comment]
@ivantopo WIP. Was working against this to build a PR for the kamon-futures repository. I think I should close this PR in favor of tracking this body of work there, no?

**Comment by ivantopo** [comment]
hey @agarbutt, yeap! better to close this one and track the progress there :smile:, and sorry, I got confused between this PR and #6.

Thanks a lot for all the efforts!

**Pull request closed without merging**
